### ISSUE TITLE
Error upon loading Private mines 

### ISSUE THREAD

**Issue by UntouchedOdin0** [knightzmc/PrivateMines#25]
I thought I'd report this bug here to make it easier to keep track 👍 

[16:07:32] [Server thread/INFO]: [PrivateMines] Enabling PrivateMines v1.2
[16:07:32] [Server thread/INFO]: Preparing start region for dimension minecraft:privatemines
[16:07:32] [Server thread/INFO]: Loaded 0 spawn chunks for world privatemines
[16:07:32] [Server thread/INFO]: Preparing spawn area: 0%
[16:07:33] [Server thread/INFO]: Preparing spawn area: 0%
[16:07:33] [Server thread/INFO]: Preparing spawn area: 0%
[16:07:33] [Server thread/INFO]: Time elapsed: 1090 ms
[16:07:33] [Server thread/INFO]: [WorldGuard] (privatemines) TNT ignition is PERMITTED.
[16:07:33] [Server thread/INFO]: [WorldGuard] (privatemines) Lighters are PERMITTED.
[16:07:33] [Server thread/INFO]: [WorldGuard] (privatemines) Lava fire is PERMITTED.
[16:07:33] [Server thread/INFO]: [WorldGuard] (privatemines) Fire spread is UNRESTRICTED.
[16:07:33] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'privatemines'
[16:07:33] [Server thread/WARN]: [PrivateMines] Could not save schematics.yml to plugins\PrivateMines\schematics\schematics.yml because schematics.yml already exists.
[16:07:33] [Server thread/INFO]: [PrivateMines] Loaded schematics.yml
[16:07:33] [Server thread/WARN]: [PrivateMines] Could not save mines.yml to plugins\PrivateMines\mines.yml because mines.yml already exists.
[16:07:33] [Server thread/ERROR]: Error occurred while enabling PrivateMines v1.2 (Is it up to date?)
java.lang.IllegalArgumentException: No Region 79e6296e-6dfb-4b13-9b27-e1b37715ce3b-mine
	at me.bristermitten.privatemines.data.MineLocations.lambda$deserialize$0(MineLocations.java:42) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]
	at me.bristermitten.privatemines.data.MineLocations.deserialize(MineLocations.java:42) ~[?:?]
	at me.bristermitten.privatemines.data.PrivateMine.deserialize(PrivateMine.java:78) ~[?:?]
	at me.bristermitten.privatemines.service.MineStorage.load(MineStorage.java:45) ~[?:?]
	at me.bristermitten.privatemines.PrivateMines.loadFiles(PrivateMines.java:195) ~[?:?]
	at me.bristermitten.privatemines.PrivateMines.onEnable(PrivateMines.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-362]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-362]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-362]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-362]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-362]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-362]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-362]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-362]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-362]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[16:07:33] [Server thread/INFO]: [PrivateMines] Disabling PrivateMines v1.2
[16:07:33] [Server thread/INFO]: [PrivateMines] Saved mines.yml

**Comment by UntouchedOdin0** [comment]
I can't reproduce as of lately but will re-open if this happens again.
